import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer/Footer";
import TopTalent from "../components/TopTalent/TopTalent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopTalent />
      <Footer></Footer>
    </div>
  );
}
